[package]
name = "model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.38"
chrono = "0.4.19"
csv = "1.1.4"
fs-err = "2.6.0"
geom = { git = "https://github.com/dabreegster/abstreet" }
serde = "1.0.123"
