[package]
name = "ui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
default = ["widgetry/native-backend"]

[dependencies]
anyhow = "1.0.38"
abstio = { git = "https://github.com/dabreegster/abstreet" }
abstutil = { git = "https://github.com/dabreegster/abstreet" }
geom = { git = "https://github.com/dabreegster/abstreet" }
model = { path = "../model" }
structopt = "0.3.23"
widgetry = { git = "https://github.com/dabreegster/abstreet" }
