[package]
name = "ui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
default = ["widgetry/native-backend"]

[dependencies]
anyhow = "1.0.38"
abstutil = { git = "https://github.com/dabreegster/abstreet" }
geom = { git = "https://github.com/dabreegster/abstreet" }
model = { path = "../model" }
widgetry = { git = "https://github.com/dabreegster/abstreet" }
